<a href="https://colab.research.google.com/github/JonghyeonWon/20261RCOSE32200/blob/main/subject1_practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 2회 데이터
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e2_p1_1.csv')
df.head(2)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,NaN,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.9,4.98,24.0
1,0.02731,NaN,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.9,9.14,21.6

In [14]:
head_index = df['CRIM'].sort_values(ascending=False).head(10).index
min_val = df['CRIM'].sort_values(ascending=False).head(10).min()
df.loc[head_index, 'CRIM'] = min_val
df.loc[df['AGE'] >= 80]['CRIM'].mean()

np.float64(5.759386625)

In [20]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e2_p1_1.csv')
df_before = df['RM'].dropna().std()
df['RM'] = df['RM'].fillna(df['RM'].median())
df_after = df['RM'].std()
round(abs(df_before - df_after),3)

0.027

In [27]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e2_p1_1.csv')
dis_average = df['DIS'].mean()
range_min = dis_average - (1.5 * df['DIS'].std())
range_max = dis_average + (1.5 * df['DIS'].std())

filter_df = df[(df['DIS'] < range_min) | (df['DIS'] > range_max)]
result = filter_df['DIS'].sum()
# result = 0
# for i in list(df['DIS']):
#   if i < range_min or range_max < i:
#     result += i;
print(result)

404.4101

In [29]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e3_p1_1.csv')
df.head(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [35]:
df_filter = df.dropna().reset_index(drop = True)
split_num = int(df_filter.shape[0] * 0.7)
round(df_filter[:split_num]['median_income'].quantile(0.25),2)

np.float64(2.51)

In [36]:

df =pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e3_p1_2.csv')
df.head()

  Country Name Country Code  Year      Value
0   Arab World          ARB  1968  2576068.3
1   Arab World          ARB  1969  2843420.4
2   Arab World          ARB  1970  3138550.0
3   Arab World          ARB  1971  3642691.0
4   Arab World          ARB  1972  4331605.7

In [39]:
mean_gdp_1990 = df[(df['Year'] == 1990)]['Value'].mean()
mean_gdp_2010 = df[(df['Year'] == 2010)]['Value'].mean()

gdp_1990_df = df[(df['Year'] == 1990)].reset_index(drop=True)
gdp_2010_df = df[(df['Year'] == 2010)].reset_index(drop=True)

filter_1990 = gdp_1990_df[gdp_1990_df['Value'] <= mean_gdp_1990]['Country Code']
filter_2010 = gdp_2010_df[gdp_2010_df['Value'] >= mean_gdp_2010]['Country Code']

len(set(filter_1990) & set(filter_2010))

5

In [42]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e3_p1_3.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3.0,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S
1,2,1,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C
2,3,1,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,C85,S
3,4,1,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,C123,S
4,5,0,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,C123,S

In [44]:
df.isnull().sum().sort_values(ascending = False)

Fare           69
Sex            64
Name           61
Cabin          58
Pclass         55
SibSp          55
Parch          53
Embarked       49
Age            44
Ticket         34
PassengerId     0
Survived        0
dtype: int64

In [46]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e4_p1_2.csv')
df.head(5)

,Title,Video ID,Published At,Keyword,Likes,Comments,Views
0,Apple Pay Is Killing the Physical Wallet After...,wAZZ-UWGVHI,2022-08-23,tech,3407.0,672.0,135612.0
1,The most EXPENSIVE thing I own.,b3x28s61q3c,2022-08-24,tech,76779.0,4306.0,1758063.0
2,My New House Gaming Setup is SICK!,4mgePWWCAmA,2022-08-23,tech,63825.0,3338.0,1564007.0
3,Petrol Vs Liquid Nitrogen | Freezing Experimen...,kXiYSI7H2b0,2022-08-23,tech,71566.0,1426.0,922918.0
4,Best Back to School Tech 2022!,ErMwWXQxHp0,2022-08-08,tech,96513.0,5155.0,1855644.0

In [50]:
int(df[(df['Likes'] / df['Comments']) >= 20 & (df['Keyword'] == 'minecraft')]['Views'].mean())

11659664

In [51]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e4_p1_3.csv')
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [53]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e5_p1_1_.csv')
df.head(5)

,시도명,시군구명,종량제봉투종류,종량제봉투처리방식,종량제봉투용도,종량제봉투사용대상,1L가격,1.5L가격,2L가격,2.5L가격,...,60L가격,75L가격,100L가격,120L가격,125L가격,관리부서명,관리부서전화번호,데이터기준일자,제공기관코드,제공기관명
0,경기도,안양시,규격봉투,매립용,생활쓰레기,사업장용,0,0,0,0,...,0,2100,0,0,0,자원순환과,031-8045-5448,2022-08-12,3830000,경기도 안양시
1,경기도,안양시,규격봉투,매립용,생활쓰레기,기타,0,0,0,0,...,0,2100,0,0,0,자원순환과,031-8045-5448,2022-08-12,3830000,경기도 안양시
2,경기도,안양시,규격봉투,소각용,음식물쓰레기,가정용,0,50,0,80,...,0,0,0,0,0,자원순환과,031-8045-5448,2022-08-12,3830000,경기도 안양시
3,경기도,안양시,규격봉투,소각용,음식물쓰레기,사업장용,0,50,0,80,...,0,0,0,0,0,자원순환과,031-8045-5448,2022-08-12,3830000,경기도 안양시
4,경기도,안양시,규격봉투,소각용,음식물쓰레기,기타,0,50,0,80,...,0,0,0,0,0,자원순환과,031-8045-5448,2022-08-12,3830000,경기도 안양시

In [56]:
df_filter = df[(df['20L가격'] != 0) & (df['5L가격'] != 0)].reset_index(drop = True)
df_filter['차이가격'] = df_filter['20L가격'] - df_filter['5L가격']
round(df_filter.groupby('시도명')['차이가격'].mean().max(),1)

619.0