<a href="https://colab.research.google.com/github/JonghyeonWon/20261RCOSE32200/blob/main/subject1_practice3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/refs/heads/master/krdatacertificate/10/p1.csv')
df.head()

    기업ID              사원ID  성별    년도   기본급   성과급
0   ID_7  cc206f1ac3c34e2e  여성  2022  3971  1708
1   ID_5  0c764af55f1b4737  남성  2025  6594  1985
2   ID_8  09d09637b617405d  여성  2020  3413  1839
3  ID_10  18588ac04b8d4da1  남성  2022  4039   741
4   ID_9  2a3a7b4e92d54f24  여성  2021  5458  1122

In [11]:
df['총수령액'] = df['기본급'] + df['성과급']
group_df = df.groupby(['년도','기업ID','성별'])['총수령액'].mean()
# group_df.unstack()
groupdf = group_df.reset_index()
pivotdf = groupdf.pivot_table(index = ['년도','기업ID'], columns = '성별', values = '총수령액')
pivotdf['차이'] = abs(pivotdf['남성'] - pivotdf['여성'])
pivotdf['차이'].sort_values().index[-1][1]

'ID_5'

In [12]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/refs/heads/master/krdatacertificate/10/p2.csv')
df.head()

,연도,구분,범죄유형1,범죄유형2,범죄유형3,범죄유형4,범죄유형5,범죄유형6,범죄유형7,범죄유형8,범죄유형9,범죄유형10
0,2013,검거건수,409,385,365,568,334,235,606,371,214,535
1,2013,발생건수,599,472,630,805,453,453,816,653,406,609
2,2014,검거건수,514,377,384,435,348,300,453,440,204,519
3,2014,발생건수,580,457,617,807,450,444,825,630,398,600
4,2015,검거건수,339,339,378,573,321,249,741,492,341,508

In [30]:
df1 = df[df['구분'] == '검거건수'].reset_index(drop=True)
df2 = df[df['구분'] == '발생건수'].reset_index(drop=True)
dfratio = df1.iloc[:,2:] / df2.iloc[:,2:]
# dfratio['연도'] = df1['연도']

# idxmax 활용
idxmax_df = pd.DataFrame()
idxmax_df['maxtype'] = dfratio.idxmax(axis=1).values
idxmax_df['연도'] = df1['연도']

idxmax_df['index'] = idxmax_df['maxtype'].str.replace('범죄유형', '').astype('int') + 1
result = 0
idx = 0
for i in idxmax_df['index'].values:
  result += df1.iloc[idx, i]
  idx += 1
result

np.int64(5421)

In [31]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/refs/heads/master/krdatacertificate/10/p3.csv')
df.head()

         사원ID  부서 성과등급  근속연수  교육참가횟수  평균만족도
0  bc614i291w  YD    S  20.0      16    3.0
1  r3mo07nkph  YA    C  19.0      15    0.6
2  09eletgw7j  YE    B  11.0       8    0.3
3  mbgotr1rla  YB    A   8.0       6    2.1
4  zi5yoj1iy6  YD    B  10.0      12    2.9

In [42]:
df['평균만족도'] = df['평균만족도'].fillna(df['평균만족도'].mean())
df['근속연수'] = df['근속연수'].fillna(df.groupby(['부서', '성과등급'])['근속연수'].transform('mean').round())
a = df[(df['부서'] == 'YA') & (df['성과등급'] == 'B')]['근속연수'].mean()
b= df[(df['부서'].str.contains('X')) &(df['평균만족도'] >= 3.2)]['교육참가횟수'].mean()
round(a+b, 3)

np.float64(22.069)