<a href="https://colab.research.google.com/github/JonghyeonWon/20261RCOSE32200/blob/main/subject1_practice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e6_p1_1.csv')
df.head(5)

,구급보고서번호,소방서명,환자증상구분명1,신고일자,신고시각,출동일자,출동시각,환자직업명,사고발생장소
0,20211122103M01526,중랑소방서,심계항진,20210330,104800,20210330,105042,무직,집
1,20211111105M00771,노원소방서,복통,20210412,225600,20210412,225827,기타,집
2,20211115104M00864,서초소방서,심계항진,20210303,194100,20210303,194500,직장인,상업시설
3,20211113107M01869,마포소방서,고열,20211225,235400,20211226,331,유아,집
4,20211118102M05820,강동소방서,고열,20211019,12100,20211019,12322,무직,집

In [17]:
df['출동시간'] = pd.to_datetime(df['출동일자'].astype('str') + \
                 df['출동시각'].astype('str').str.zfill(6))
df['신고시간'] = pd.to_datetime(df['신고일자'].astype('str') + \
                 df['신고시각'].astype('str').str.zfill(6))
df['소요시간'] = df['출동시간'] - df['신고시간']
df['소요시간'] = df['소요시간'].dt.total_seconds()

new_df = df.groupby('소방서명')['소요시간'].mean()
new_df.sort_values()

소방서명
서초소방서     164.883495
서대문소방서    165.056604
종로소방서     175.500000
광진소방서     175.602273
노원소방서     179.579310
강동소방서     181.656566
동작소방서     185.107527
송파소방서     189.330508
구로소방서     189.513274
은평소방서     191.390071
양천소방서     192.201389
마포소방서     196.547445
강남소방서     196.933333
강서소방서     199.696203
중랑소방서     204.877049
성북소방서     205.293578
도봉소방서     207.145631
성동소방서     207.358209
중부소방서     207.563636
관악소방서     209.843750
강북소방서     212.061224
동대문소방서    228.148515
용산소방서     237.366197
영등포소방서    258.839286
Name: 소요시간, dtype: float64

In [18]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e6_p1_2.csv')
df.head(5)

               학교명  시도  학교세부유형  일반학급_학생수_계  교원수_총계_계
0  서울대학교사범대학부설고등학교  서울  일반고등학교         689        73
1           가락고등학교  서울  일반고등학교         765        70
2           개포고등학교  서울  일반고등학교         684        69
3           경기고등학교  서울  일반고등학교        1047        96
4           경동고등학교  서울  일반고등학교         529        58

In [43]:
local = df[df['학교세부유형'] == '일반중학교']['시도'].value_counts().index[1]
df_filter = df[(df['시도'] == local) & (df['학교세부유형'] == '일반중학교')]
df_filter['target'] = df['일반학급_학생수_계'] / df['교원수_총계_계']
df_filter.sort_values('target', ascending=False)['교원수_총계_계'].values[0]

/tmp/ipykernel_706/1926698044.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['target'] = df['일반학급_학생수_계'] / df['교원수_총계_계']

np.int64(33)

In [44]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e6_p1_3.csv')
df.head(5)

       범죄분류     절도     사기   배임   방화     폭행
0  2018년_1월  13280  25318  656  143  12186
1  2018년_2월  12504  19159  403  135  12087
2  2018년_3월  14733  24509  471  148  13841
3  2018년_4월  14781  23147  414  135  13973
4  2018년_5월  15988  23584  451  127  14117

In [60]:
df['총범죄수'] = df['절도'] + df['사기'] + df['배임'] + df['방화'] + df['폭행']
df['분기'] = ['18_1','18_1','18_1',
            '18_2','18_2','18_2',
            '18_3','18_3','18_3',
            '18_4','18_4','18_4',
            '19_1','19_1','19_1',
            '19_2','19_2','19_2',
            '19_3','19_3','19_3',
            '19_4','19_4','19_4']
target = df.groupby('분기')['총범죄수'].mean().sort_values().index[-1]
df[df['분기'] == target].sort_values('사기')

        범죄분류     절도     사기   배임   방화     폭행   총범죄수    분기
17  2019년_6월  16937  25822  491  101  15285  58636  19_2
15  2019년_4월  15305  27125  478  138  13322  56368  19_2
16  2019년_5월  17333  27766  509  131  14572  60311  19_2

In [73]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e7_p1.csv')
df.head(5)

     학생    국어    수학    영어    과학
0  ID_0  63.0   NaN  79.0  84.0
1  ID_1  91.0  93.0   NaN  73.0
2  ID_2  59.0  55.0   NaN  56.0
3  ID_3  71.0  83.0  82.0   NaN
4  ID_4  62.0  72.0  56.0   NaN

In [82]:
subject = df.isnull().sum().index[1]
df_filter = df[subject].dropna()
score = (df_filter - df_filter.mean()) / df_filter.std(ddof=0)
score.max()

1.713855688712825

In [83]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e7_p3.csv')
df.head(5)

,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,var_10,var_11,var_12
0,-0.401584,0.007198,-0.134910,-0.419514,-0.686331,-1.174550,-0.499150,-0.557510,0.357347,0.844209,0.082097,0.475098
1,1.064622,-0.531247,0.571185,-0.762243,-1.456043,0.355432,0.880010,0.523183,-0.141733,0.301472,0.840299,-0.045113
2,0.900195,-1.148496,-0.718437,-2.315266,-0.755505,0.630923,0.586027,0.086497,-0.381657,-1.602532,1.566340,-0.654105
3,1.199227,-0.114200,0.101536,-1.851971,-0.672844,0.796077,0.644246,-0.836296,-1.707074,0.376281,1.303967,1.228015
4,0.607393,1.675917,1.063759,-0.799493,-0.959568,-0.103007,-0.245984,-0.059492,0.293592,-0.517044,0.100772,0.403833

In [91]:
q1 = df['var_6'].quantile(0.25)
q3 = df['var_6'].quantile(0.75)
iqr = q3 - q1
lower = q1 - (1.5 * iqr)
upper = q3 + (1.5 * iqr)
df[(df['var_6'] < lower) | (df['var_6'] > upper)]['var_6'].shape[0]

8

In [92]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e8_p1_1.csv')
df.head(5)

       대륙       국가명  소비량
0  Africa   Algeria   25
1  Africa    Angola  217
2  Africa     Benin   34
3  Africa  Botswana  173
4  Africa   Burundi   88

In [98]:
region = df.groupby('대륙')['소비량'].mean().sort_values().index[-5]
df[df['대륙'] == region]['소비량'].sort_values().values[-2]

np.int64(347)

In [99]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e8_p1_2.csv')
df.head(5)

       국가       관광      방문    유학연수    취업     기타
0    뉴질랜드  24724.0  6320.0  4911.0  56.0  637.0
1    피  지   3889.0   564.0    98.0  15.0   40.0
2     벨기에    243.0    58.0    30.0   7.0   25.0
3     멕시코   1069.0   335.0   103.0  32.0   48.0
4  우즈베키스탄   3994.0  1456.0    97.0   4.0  137.0

In [110]:
df['총방문객'] = df['관광'] + df['방문'] + df['유학연수'] + df['취업'] + df['기타']
df['관광비율'] = df['관광'] / df['총방문객']
target1 = df.sort_values('관광비율',ascending = False)['국가'].values[1]
fir = df[df['국가'] == target1]['취업'].values[0]

target2 = df.sort_values('관광',ascending=False)['국가'].values[2]
sec = df[df['국가'] == target2]['방문'].values[0]

fir + sec

np.float64(30835.0)

In [111]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/krdatacertificate/e8_p1_3.csv')
df.head(5)

         Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)
0  10/03/2004  18.00.00     2.6       1360.0     150.0      11.9
1  10/03/2004  19.00.00     2.0       1292.0     112.0       9.4
2  10/03/2004  20.00.00     2.2       1402.0      88.0       9.0
3  10/03/2004  21.00.00     2.2       1376.0      80.0       9.2
4  10/03/2004  22.00.00     1.6       1272.0      51.0       6.5

In [113]:
df['co_nm'] = (df['CO(GT)'] - df['CO(GT)'].min()) / (df['CO(GT)'].max() - df['CO(GT)'].min())
df['nmhc_nm'] = (df['NMHC(GT)'] - df['NMHC(GT)'].min()) / (df['NMHC(GT)'].max() - df['NMHC(GT)'].min())
round(abs(df['co_nm'].std(ddof=0) - df['nmhc_nm'].std(ddof=0)), 3)

0.266